version: '3'

services:
  kkt-zookeeper:
    container_name: kkt-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kkt-kafka:
    container_name: kkt-kafka
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_CREATE_TOPICS: "main:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kkt-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kkt:
    container_name: kkt
    build:
      context: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHANNEL_ID: ${TELEGRAM_CHANNEL_id}
      KAFKA_HOST: kkt-kafka:9092

